routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/posts', function () {
    return view('post');
});

Auth::routes();

Route::resource('questions', 'QuestionsController')->except('show');
//Now if we write route('questions.show') it will not work bcoz we've removed it using except method.
// we have to manually write questions.show route bcoz we want to bind it using slug for questions.show only.
Route::get('questions/{slug}', 'QuestionsController@show')->name('questions.show');

Route::post('questions/{question}/favourite', 'FavouritesController@store')->name('questions.favourite');
Route::delete('questions/{question}/unfavourite', 'FavouritesController@destroy')->name('questions.unfavourite');

Route::post('questions/{question}/vote/{vote}', 'VotesController@voteQuestion')->name('questions.vote');
Route::post('answers/{answer}/vote/{vote}', 'VotesController@voteAnswer')->name('answers.vote');

Route::resource('questions.answers', 'AnswersController')->except(['show', 'index', 'create']);
Route::put('answers/{answer}/best-answer', 'AnswersController@bestAnswer')->name('answers.bestAnswer');

Route::get('users/notifications', 'UsersController@notifications')->name('users.notifications');

Route::get('/home', 'HomeController@index')->name('home');

app/Answer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    //
    protected $fillable = ['user_id', 'body'];

    public static function boot()
    {
        parent::boot(); //we have to write this line bcoz opf inheritance rule

        static::created(function ($answer) {
            $answer->question->increment('answers_count');
        });
        static::deleted(function ($answer) {
            $answer->question->decrement('answers_count');
        });
    }

    /**
     * ACCESSORS
     */

    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    public function getBestAnswerStatusAttribute()
    {
        if ($this->id === $this->question->best_answer_id) {
            return "text-success";
        }
        return "text-dark";
    }

    public function getIsBestAttribute()
    {
        return $this->id === $this->question->best_answer_id;
    }

    /**
     * Relationship Methods
     */

    public function question()
    {
        return $this->belongsTo(Question::class);
    }
    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
    public function votes()
    {
        return $this->morphToMany(User::class, 'vote')->withTimestamps();
    }

    /**
     * Helper Functions
     */

    public function vote(int $vote)
    {
        $this->votes()->attach(auth()->id(), ['vote' => $vote]);
        if ($vote < 0) {
            $this->decrement('votes_count');
        } else {
            $this->increment('votes_count');
        }
    }

    public function updateVote(int $vote)
    {
        /**
         *
         *Here we will decrement or increment by 2 times bcoz if the user has already upvoted to a question and that question has votes_count = 10 so without that user's upvote votes_count will be 9 and it that user has down-voted then votes_count should be 8.
         * same is the case for vice versa.
         */
        $this->votes()->updateExistingPivot(auth()->id(), ['vote' => $vote]);
        // pivot columns are those columns which are in bridging table but not related to some other table like user_id,question_id,etc.
        // Here pivot column is vote which is not related to any table but we need that column.
        // we can update pivot columns by using updateExistingPivotMethod
        // Here we can ensure that user has already voted to an answer and now that user wants to update his vote for that answer.
        // so we are passing user_id bcoz it is the foreign_key
        //         Updating A Record On A Pivot Table
        // If you need to update an existing row in your pivot table, you may use updateExistingPivot method. This method accepts the pivot record foreign key and an array of attributes to update.
        // $user = App\User::find(1);

        // $user->roles()->updateExistingPivot($roleId, $attributes);
        if ($vote < 0) {
            $this->decrement('votes_count');
            $this->decrement('votes_count');
        } else {
            $this->increment('votes_count');
            $this->increment('votes_count');
        }
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;


class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * ACCESSORS
     */
    public function getAvatarAttribute()
    {
        $name = $this->name;
        $size = 40;
        return "https://ui-avatars.com/api/?name=$name&size=$size";
    }

    /**
     * Relationship Methods
     */
    public function questions()
    {
        return $this->hasMany(Question::class);
    }

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }

    public function favourites()
    {
        return $this->belongsToMany(Question::class)->withTimestamps();
    }

    public function votesQuestions()
    {
        return $this->morphedByMany(Question::class, 'vote')->withTimestamps();
    }

    public function votesAnswers()
    {
        return $this->morphedByMany(Answer::class, 'vote')->withTimestamps();
    }




    /**
     * Helper Functions
     */
    public function hasQuestionUpVote(Question $question)
    {
        return auth()->user()->votesQuestions()->where(['vote' => 1, 'vote_id' => $question->id])->exists();
    }

    public function hasQuestionDownVote(Question $question)
    {
        return auth()->user()->votesQuestions()->where(['vote' => -1, 'vote_id' => $question->id])->exists();
    }

    public function hasVoteForQuestion(Question $question)
    {
        return $this->hasQuestionUpVote($question) || $this->hasQuestionDownVote($question);
    }


    public function hasAnswerUpVote(Answer $answer)
    {
        return auth()->user()->votesAnswers()->where(['vote' => 1, 'vote_id' => $answer->id])->exists();
    }

    public function hasAnswerDownVote(Answer $answer)
    {
        return auth()->user()->votesAnswers()->where(['vote' => -1, 'vote_id' => $answer->id])->exists();
    }

    public function hasVoteForAnswer(Answer $answer)
    {
        return $this->hasAnswerUpVote($answer) || $this->hasAnswerDownVote($answer);
    }
}

app/Http/Controllers/AnswersController.php
<?php

namespace App\Http\Controllers;

use App\Answer;
use App\Http\Requests\CreateNewAnswerRequest;
use App\Http\Requests\UpdateAnswerRequest;
use App\Notifications\BestAnswerNotification;
use App\Notifications\NewReplyAdded;
use App\Question;
use Illuminate\Http\Request;

class AnswersController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateNewAnswerRequest $request, Question $question)
    {
        //
        $question->answers()->create([
            'user_id' => auth()->id(),
            'body' => $request->body
        ]);

        $question->owner->notify(new NewReplyAdded($question));
        session()->flash('success', 'Your answer has been submitted successfully');
        return redirect(route('questions.show', $question->slug));
    }

    public function edit(Question $question, Answer $answer)
    {
        $this->authorize('update', $answer);
        return view('answers._edit', compact(['answer', 'question']));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateAnswerRequest $request, Question $question, Answer $answer)
    {
        //
        $answer->update([
            'body' => $request->body
        ]);
        session()->flash('success', 'Your answer has been updated successfully');
        return redirect($question->url);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question, Answer $answer)
    {
        //

        $this->authorize('markAsBest', $answer); //if authorize returns false then it automatically goes to 403.
        $answer->delete();
        session()->flash('success', 'Your answer has been Deleted successfully');
        return redirect($question->url);
    }

    public function bestAnswer(Request $request, Answer $answer)
    {
        $this->authorize('markAsBest', $answer); //if authorize returns false then it automatically goes to 403.
        $answer->question->markAsBest($answer);
        $answer->author->notify(new BestAnswerNotification($answer->question));
        return redirect()->back();
    }
}

resources/views/answers/_create.blade.php
@auth

<div class="row mt-5">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3>Your Answer</h3>
            </div>
            <div class="card-body">
            <form action="{{ route('questions.answers.store',$question->id) }}" method="POST">
                @csrf
                <div class="form-group">
                    <input type="hidden" id="body" name="body" value="{{ old('body') }}">
                    <trix-editor input="body"></trix-editor>
                    @error('body')
                        <div class="text-danger">{{$message}}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-outline-primary">Submit</button>
                </div>
            </form>
            </div>
        </div>
    </div>
</div>
@endauth

resources/views/answers/_edit.blade.php
@extends('layouts.app')

@section('styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.css">
@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.js"></script>
@endsection

@section('content')
    <div class="container">
        <div class="row mt-5">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3>Your Answer</h3>
                    </div>
                    <div class="card-body">
                    <form action="{{ route('questions.answers.update',[$question->id,$answer->id]) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <input type="hidden" id="body" name="body" value="{{ old('body',$answer->body) }}">
                            <trix-editor input="body"></trix-editor>
                            @error('body')
                                <div class="text-danger">{{$message}}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-outline-primary">Submit</button>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

resources/views/answers/_index.blade.php
        <div class="row mt-4">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="mt-0">
                            {{ Str::plural('Answer', $question->answers_count) }}
                        </h3>
                    </div>
                    <div class="card-body">
                        @foreach($question->answers as $answer)
                            <div class="d-flex">
                                <div class="d-flex flex-column">
                                    <div>
                                        @can('vote', $answer)
                                            @if (!auth()->user()->hasAnswerUpVote($answer))
                                                <form action="{{ route('answers.vote',[$answer->id,1]) }}" method="post">
                                                    @csrf
                                                    <button type="submit"
                                                    class="btn {{ auth()->user()->hasAnswerUpVote($answer) ? 'text-dark' : 'text-black-50' }}">
                                                        <i class="fa fa-caret-up fa-3x"></i>
                                                    </button>
                                                </form>
                                            @else
                                                <div class="d-flex justify-content-center mb-2">
                                                    <i class="fa fa-caret-up fa-3x"></i>
                                                </div>
                                            @endif
                                        @endcan
                                        @guest
                                            <a href="{{ route('login') }}" title="Up Vote" class="vote-up d-block text-center text-black-50">
                                                <i class="fa fa-caret-up fa-3x"></i>
                                            </a>
                                        @endguest
                                    <div class="{{ auth()->id() === $answer->user_id ? 'd-flex flex-column mt-2' : '' }}">
                                        <h4 class="text-muted text-center m-0">{{ $answer->votes_count }}</h4>
                                        @if (auth()->id() === $answer->user_id)
                                            <p class="text-muted lead text-center mt-1">Votes</p>
                                        @else

                                        @endif
                                    </div>
                                    @can('vote', $answer)
                                        @if (!auth()->user()->hasAnswerDownVote($answer))
                                            <form action="{{ route('answers.vote',[$answer->id,-1]) }}" method="post">
                                                @csrf
                                                <button type="submit"
                                                class="btn {{ auth()->user()->hasAnswerDownVote($answer) ? 'text-dark' : 'text-black-50' }}">
                                                    <i class="fa fa-caret-down fa-3x"></i>
                                                </button>
                                            </form>
                                        @else
                                            <div class="d-flex justify-content-center mb-2">
                                                <i class="fa fa-caret-down fa-3x"></i>
                                            </div>
                                        @endif
                                    @endcan
                                    @guest
                                        <a href="{{ route('login') }}" title="Up Vote" class="vote-down d-block text-center text-black-50">
                                            <i class="fa fa-caret-down fa-3x"></i>
                                        </a>
                                    @endguest
                                    </div>

                                    <div class="mt-2">
                                        @can('markAsBest', $answer)
                                            <form action="{{ route('answers.bestAnswer',$answer->id) }}" method="post">
                                                    @csrf
                                                    @method('PUT')
                                                <button type="submit" class="btn {{ $answer->best_answer_status }}"><i class="fa fa-check fa-2x"></i></button>
                                            </form>
                                        @else
                                            @if ($answer->is_best)
                                                <i class="fa fa-check fa-2x d-block text-success mb-3"></i>
                                            @endif
                                        @endcan
                                    </div>
                                </div>
                                <div class="ml-5">
                                    {!! $answer->body !!}
                                </div>
                            </div>
                            <div class="d-flex justify-content-between mr-3">
                                <div class="d-flex">
                                    <div class="mr-2">
                                        @can('update', $answer)
                                            <a href="{{ route('questions.answers.edit',[$question->id,$answer->id]) }}" class="btn btn-outline-info">Edit</a>
                                        @endcan
                                    </div>
                                    @can('delete', $answer)
                                        <form action="{{ route('questions.answers.destroy',[$question->id,$answer->id]) }}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-outline-danger" onclick="return confirm('Are You sure u want to delete the answer?');">Delete</button>
                                        </form>
                                    @endcan
                                </div>
                                <div class="d-flex flex-column">
                                    <div class="text-muted mb-2 text-right">
                                        Answered {{ $answer->created_date }}
                                    </div>
                                    <div class="d-flex mb-2">
                                        <div>
                                            <img src="{{ $answer->author->avatar }}" alt="">
                                        </div>
                                        <div class="mt-2 ml-2">
                                            {{ $answer->author->name }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>