routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/posts', function () {
    return view('post');
});

Auth::routes();

Route::resource('questions', 'QuestionsController')->except('show');
//Now if we write route('questions.show') it will not work bcoz we've removed it using except method.
// we have to manually write questions.show route bcoz we want to bind it using slug for questions.show only.
Route::get('questions/{slug}', 'QuestionsController@show')->name('questions.show');

Route::post('questions/{question}/favourite', 'FavouritesController@store')->name('questions.favourite');
Route::delete('questions/{question}/unfavourite', 'FavouritesController@destroy')->name('questions.unfavourite');

Route::post('questions/{question}/vote/{vote}', 'VotesController@voteQuestion')->name('questions.vote');
Route::post('answers/{answer}/vote/{vote}', 'VotesController@voteAnswer')->name('answers.vote');

Route::resource('questions.answers', 'AnswersController')->except(['show', 'index', 'create']);
Route::put('answers/{answer}/best-answer', 'AnswersController@bestAnswer')->name('answers.bestAnswer');

Route::get('users/notifications', 'UsersController@notifications')->name('users.notifications');

Route::get('/home', 'HomeController@index')->name('home');

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Question extends Model
{
    protected $fillable = ['title', 'body'];
    /**
     * Relationship Methods
     */
    public function owner()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }

    public function favourites()
    {
        return $this->belongsToMany(User::class)->withTimestamps();
    }

    public function votes()
    {
        return $this->morphToMany(User::class, 'vote')->withTimestamps();
    }

    /**
     * MUTATORS
     * These are special functions which have setXXXAttribute($value).
     * Here func_name is setTitleAttribute so when we set the title attribute of an object of Question this method will be automativally called and will do its work.
     */
    public function setTitleAttribute($title)
    {
        $this->attributes['title'] = $title;
        $this->attributes['slug'] = Str::slug($title);
    }

    /**
     * ACCESSORS
     * These are special functions which have getXXXAttribute().
     * Here func_name is getUrlAttribute so whereever we write $questionObj->url it will automatically call this function and return the url.
     * Note if $questionObj dont have any url then it will bring null or ''.
     */
    public function getUrlAttribute()
    {
        return "questions/{$this->slug}";
    }

    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    public function getAnswersStyleAttribute()
    {
        if ($this->answers_count > 0) {
            if ($this->best_answer_id) {
                return 'has-best-answer';
            }
            return 'answered';
        }
        return 'unanswered';
    }

    public function getFavouritesCountAttribute()
    {
        return $this->favourites->count();
    }

    public function getIsFavouriteAttribute()
    {
        return $this->favourites()->where(['user_id' => auth()->id()])->count() > 0;
        // this above query will search for a record in question_user where question_id = $this->id and user_id = auth()->id()
        // u can verify by writing this query in tinker
        // $question->favourites()->where('user_id','1')->toSql()
    }

    /**
     * Helper Functions
     */
    public function markAsBest(Answer $answer)
    {
        $this->best_answer_id = $answer->id;
        $this->save();
    }

    public function vote(int $vote)
    {
        $this->votes()->attach(auth()->id(), ['vote' => $vote]);
        if ($vote < 0) {
            $this->decrement('votes_count');
        } else {
            $this->increment('votes_count');
        }
    }

    public function updateVote(int $vote)
    {
        /**
         *
         *Here we will decrement or increment by 2 times bcoz if the user has already upvoted to a question and that question has votes_count = 10 so without that user's upvote votes_count will be 9 and it that user has down-voted then votes_count should be 8.
         * same is the case for vice versa.
         */
        $this->votes()->updateExistingPivot(auth()->id(), ['vote' => $vote]);
        if ($vote < 0) {
            $this->decrement('votes_count');
            $this->decrement('votes_count');
        } else {
            $this->increment('votes_count');
            $this->increment('votes_count');
        }
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;


class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * ACCESSORS
     */
    public function getAvatarAttribute()
    {
        $name = $this->name;
        $size = 40;
        return "https://ui-avatars.com/api/?name=$name&size=$size";
    }

    /**
     * Relationship Methods
     */
    public function questions()
    {
        return $this->hasMany(Question::class);
    }

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }

    public function favourites()
    {
        return $this->belongsToMany(Question::class)->withTimestamps();
    }

    public function votesQuestions()
    {
        return $this->morphedByMany(Question::class, 'vote')->withTimestamps();
    }

    public function votesAnswers()
    {
        return $this->morphedByMany(Answer::class, 'vote')->withTimestamps();
    }




    /**
     * Helper Functions
     */
    public function hasQuestionUpVote(Question $question)
    {
        return auth()->user()->votesQuestions()->where(['vote' => 1, 'vote_id' => $question->id])->exists();
    }

    public function hasQuestionDownVote(Question $question)
    {
        return auth()->user()->votesQuestions()->where(['vote' => -1, 'vote_id' => $question->id])->exists();
    }

    public function hasVoteForQuestion(Question $question)
    {
        return $this->hasQuestionUpVote($question) || $this->hasQuestionDownVote($question);
    }


    public function hasAnswerUpVote(Answer $answer)
    {
        return auth()->user()->votesAnswers()->where(['vote' => 1, 'vote_id' => $answer->id])->exists();
    }

    public function hasAnswerDownVote(Answer $answer)
    {
        return auth()->user()->votesAnswers()->where(['vote' => -1, 'vote_id' => $answer->id])->exists();
    }

    public function hasVoteForAnswer(Answer $answer)
    {
        return $this->hasAnswerUpVote($answer) || $this->hasAnswerDownVote($answer);
    }
}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Questions\CreateQuestionRequest;
use App\Http\Requests\Questions\UpdateQuestionRequest;
use App\Question;
use Illuminate\Support\Facades\Gate;
use Illuminate\Http\Request;

class QuestionsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->only(['create', 'store', 'edit', 'update']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $questions = Question::with('owner')->latest()->paginate(10); //will eager load the records.
        // with method preloads the relationship which is specified.
        // E.g. without with method
        // Here is the scenario where we want owner name of all the questions
        /**
         * Here problem is there if we do this :
         * $questions = Question::latest()->paginate(10);
         * Bcoz in questions.index we are writing $question->owner and it will run 10 times bcoz we had written paginate(10).
         * Now the problem is every time $question->owner it goes to users table and fetch the record.
         * that means if i have 25 records per page then no of queries executed will be 25+1=26.
         * 1 query for extracting the 25 records and 25 queries to get the name of the owner.
         * This problem is known as n+1 query problem and lazy loading.
         */
        return view('questions.index', compact([
            'questions'
        ]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        app('debugbar')->disable();
        return view('questions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateQuestionRequest $request)
    {
        //
        auth()->user()->questions()->create([
            'title' => $request->title,
            'body' => $request->body
        ]);

        session()->flash('success', 'Questions has been added successfully!');
        return redirect(route('questions.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function show(Question $question)
    {
        //Refer notes.txt
        $question->increment('views_count'); //this will increment the views_count every time we see any question.
        return view('questions.show', compact('question'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        //
        if ($this->authorize('update', $question)) {
            app('debugbar')->disable();
            return view('questions.edit', compact('question'));
        }
        abort(403);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateQuestionRequest $request, Question $question)
    {
        //

        if ($this->authorize('update', $question)) {
            $question->update([
                'title' => $request->title,
                'body' => $request->body
            ]);

            session()->flash('success', 'Questions has been updated successfully!');
            return redirect(route('questions.index'));
        }
        abort(403);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        //
        if ($this->authorize('delete', $question)) {
            $question->delete();
            session()->flash('success', 'Questions has been Deleted successfully!');
            return redirect(route('questions.index'));
        }
        abort(403);
    }
}

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3>Ask a Question</h3>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('questions.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text"
                                name="title"
                                id="title"
                                placeholder="Enter Title"
                                value="{{ old('title') }}" class="form-control @error('title') is-invalid @enderror " >
                                @error('title')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                            <div class="form-group">
                                <input type="hidden" id="body" name="body" value="{{ old('body') }}">
                                <trix-editor input="body"></trix-editor>
                                @error('body')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-success">Post a Question!</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.js"></script>
@endsection

@section('styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.css">
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3>Edit Question</h3>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('questions.update',$question->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text"
                                name="title"
                                id="title"
                                placeholder="Enter Title"
                                value="{{ old('title',$question->title) }}" class="form-control @error('title') is-invalid @enderror " >
                                @error('title')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                            <div class="form-group">
                                <input type="hidden" id="body" name="body" value="{{ old('body',$question->body) }}">
                                <trix-editor input="body"></trix-editor>
                                @error('body')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-success">Post a Question!</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.js"></script>
@endsection

@section('styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.css">
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')

@section('styles')
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            @include('layouts.partials._message')
            <div class="d-flex justify-content-end mb-3">
                <a href="{{ route('questions.create') }}" class="btn btn-outline-primary">Ask a Question</a>
            </div>
            <div class="card">
                <div class="card-header">All Questions</div>
                @foreach ($questions as $question)
                    <div class="card-body">
                        <div class="media">
                            <div class="d-flex flex-column statistics mr-3">
                                <div class="votes text-center mb-3">
                                <strong class="d-block">{{ $question->votes_count }}</strong>
                                Votes
                                </div>
                                <div class="answers text-center mb-3">
                                <strong class="d-block answers {{ $question->answers_style }}">
                                        {{ $question->answers_count }}
                                    </strong>
                                    Answers
                                </div>
                                <div class="views text-center">
                                    <strong class="d-block">
                                        {{ $question->views_count }}
                                    </strong>
                                Views
                                </div>
                            </div>
                            <div class="media-body">
                            <div class="d-flex justify-content-between">
                                <h4>
                                    <a href="{{ $question->url }}">{{ $question->title }}</a>
                                    @if ($question->is_favourite)
                                        <i class="fa fa-star text-warning"></i>
                                    @endif
                                </h4>
                                <div class="buttons d-flex">

                                        @can('update', $question)

                                            {{-- @can will call specified method of QuestionsPolicy with Question object and based of the result it will show the edit button --}}
                                            <div class="">
                                                <a href="{{ route('questions.edit',$question->id) }}" class="btn btn-outline-info mr-2">Edit</a>
                                            </div>
                                        @endcan
                                        @can('delete', $question)
                                            <form action="{{ route('questions.destroy',$question->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" onclick="return confirm('Are u sure u want to delete?');" class="btn btn-outline-danger">Delete</button>
                                            </form>
                                        @endcan
                                </div>
                            </div>
                            <p>
                                Asked By: <a href="#">{{ $question->owner->name }}</a>
                            <span class="text-muted"> | Asked : {{ $question->created_date }}</span>
                            </p>
                            <p>{{ strip_tags(Str::limit($question->body,250)) }}</p>
                            {{-- <p>Niraj</p><p>Bathija</p>  -> strip_tags will give like this NirajBathija it will not show it like html means it will not show heading text like headings and all other styles.strip_tags returns normal string and it just removes the tags between text. --}}
                            </div>
                        </div>
                    </div>
                    <hr>
                @endforeach
                <div class="card-footer">
                    {{ $questions->links() }}
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')

@section('styles')
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.css">
@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.js"></script>
@endsection

@section('content')
    <div class="container">
        @include('layouts.partials._message')
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h1>{{ $question->title }}</h1>
                    </div>
                    <div class="card-body">
                        {!! $question->body !!}
                    </div>
                    <div class="card-footer">
                        <div class="d-flex justify-content-between mr-3">
                            <div class="d-flex">
                                <div>
                                    @can('vote', $question)
<<<<<<< HEAD
                                        <form action="{{ route('questions.vote',[$question->id,1]) }}" method="post">
                                            @csrf
                                            <button type="submit"
                                            class="btn {{ auth()->user()->hasQuestionUpVote($question) ? 'text-dark' : 'text-black-50' }}">
=======
                                        @if (!auth()->user()->hasQuestionUpVote($question))
                                            <form action="{{ route('questions.vote',[$question->id,1]) }}" method="post">
                                                @csrf
                                                <button type="submit"
                                                class="btn {{ auth()->user()->hasQuestionUpVote($question) ? 'text-dark' : 'text-black-50' }}">
                                                    <i class="fa fa-caret-up fa-3x"></i>
                                                </button>
                                            </form>
                                        @else
                                            <div class="text-dark d-flex justify-content-center mb-2">
>>>>>>> Votes-feature
                                                <i class="fa fa-caret-up fa-3x"></i>
                                            </div>
                                        @endif
                                    @endcan
                                    @guest
                                        <a href="{{ route('login') }}" title="Up Vote" class="vote-up d-block text-center text-black-50">
                                            <i class="fa fa-caret-up fa-3x"></i>
                                        </a>
                                    @endguest
                                    <div class="{{ auth()->id() === $question->user_id ? 'd-flex flex-column mt-2' : '' }}">
                                        <h4 class="text-muted text-center m-0">{{ $question->votes_count }}</h4>
                                        @if (auth()->id() === $question->user_id)
                                            <p class="text-muted lead mt-1">Votes</p>
                                        @else

                                        @endif
                                    </div>
                                    @can('vote', $question)
                                        @if (!auth()->user()->hasQuestionDownVote($question))
                                            <form action="{{ route('questions.vote',[$question->id,-1]) }}" method="post">
                                                @csrf
                                                <button type="submit"
                                                class="btn {{ auth()->user()->hasQuestionDownVote($question) ? 'text-dark' : 'text-black-50' }}">
                                                    <i class="fa fa-caret-down fa-3x"></i>
                                                </button>
                                            </form>
                                        @else
                                            <div class="text-dark d-flex justify-content-center mb-2">
                                                <i class="fa fa-caret-down fa-3x"></i>
                                            </div>
                                        @endif
                                    @endcan
                                    @guest
                                        <a href="{{ route('login') }}" title="Up Vote" class="vote-down d-block text-center text-black-50">
                                            <i class="fa fa-caret-down fa-3x"></i>
                                        </a>
                                    @endguest
                                </div>

                                <div class="ml-5 mt-2 {{ $question->is_favourite ? 'text-warning' : 'text-black-50'  }}">
                                    @can('markAsFavourite', $question)

                                        <form action="{{ route($question->is_favourite ? 'questions.unfavourite' : 'questions.favourite',$question->id) }}" method="post">

                                            @csrf

                                            @if ($question->is_favourite)
                                                @method('DELETE')
                                            @endif

                                            <button type="submit"
                                            class="btn {{ $question->is_favourite ? 'text-warning' : 'text-black-50' }}">

                                                <i class="fa {{ $question->is_favourite ? 'fa-star' : 'fa-star-o' }} fa-2x"></i>

                                            </button>
                                        </form>
                                        <h4 class="votes-count m-0 text-center text-black-50">{{ $question->favourites_count }}</h4>

                                    @else
                                        <i class="fa fa-star-o fa-2x text-black-50"></i>
                                        <h4 class="votes-count m-0 text-center text-black-50">{{ $question->favourites_count }}</h4>

                                    @endcan
                                </div>
                            </div>
                            <div class="d-flex flex-column">
                                <div class="text-muted mb-2 text-right">
                                    Asked {{ $question->created_date }}
                                </div>
                                <div class="d-flex mb-2">
                                    <div>
                                        <img src="{{ $question->owner->avatar }}" alt="">
                                    </div>
                                    <div class="mt-2 ml-2">
                                        {{ $question->owner->name }}
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!--ANSWERS-->
        @include('answers._index')

        @include('answers._create')
    </div>
@endsection